apiVersion: v1
kind: Peer
metadata:
  name: snowflake_warehouse
  environment: production
  description: Snowflake data warehouse
spec:
  type: snowflake
  config:
    account_id: ${SNOWFLAKE_ACCOUNT}
    username: peerdb_user
    private_key: ${SNOWFLAKE_PRIVATE_KEY}  # RSA private key
    database: ANALYTICS_DB
    warehouse: COMPUTE_WH
    role: PEERDB_ROLE
    query_timeout: 300
    metadata_schema: _PEERDB_INTERNAL
  validation:
    timeout: 45s
    retry_attempts: 3
